### ISSUE TITLE
Plugin not compatible with IntelliJ IDEA 2020.2

### ISSUE THREAD

**Issue by krzysztof-jelski** [intellij-solidity/intellij-solidity#197]
Fails with

`java.lang.NoClassDefFoundError: com/intellij/openapi/compiler/CompilerFactory`

**Comment by mbolotov** [comment]
Hi @krzysztof-jelski!
I took a look into the problem. The `CompilerFactory` issue itself can be easy fixed by adding 
`<depends>com.intellij.modules.java</depends>` into the plugin descriptor file.
But the problem is that there are many other api incompatibilities  when migrating from 2016 to 2020.2 platform version. 
Not sure if I can fix this quickly. 
@SerCeMan do you have any plans to migrate to 2020 idea platform?

**Comment by SerCeMan** [comment]
Hey, folks! I'll take a look in the next couple of weeks. Although, I feel like modularisation, and extracting the complier into its separate plugin would be the true north star here.

**Comment by SerCeMan** [comment]
Hey, @krzysztof-jelski! The new [2.2.0](https://github.com/intellij-solidity/intellij-solidity/releases/tag/2.2.0) version supports 2020.1+. It's currently undergoing a JB review and should appear in the marketplace in the next few days. In the meantime, you can install and test it by installing the new version directly from [here](https://github.com/intellij-solidity/intellij-solidity/releases/tag/2.2.0).
